### ISSUE TITLE
change mode on socket on detach

### ISSUE THREAD

**Issue by anarcat** [crigler/dtach#17]
it would be nice if detach would allow for a way to figure out if a session is attached or not. screen uses the execute bit on the socket to document this: when a session is attached, it's executable, when it's not, it's not.

irssi can use that to automatically mark users as away for example.

**Comment by mrichar1** [comment]
It appears that this behaviour is already present in `dtach`:

```
$ dtach -A foo.sock bash
$ ls -l foo.sock
srwx------ 1 mrichar1 mrichar1 0 Nov 12 19:57 foo.sock
<ctrl-\>
$ ls -l foo.sock
srw------- 1 mrichar1 mrichar1 0 Nov 12 19:57 foo.sock
```

**Comment by anarcat** [comment]
well dang. i could have sworn that wasn't the case. now i can write an irssi plugin, thanks! https://github.com/irssi/scripts.irssi.org/pull/677
