### ISSUE TITLE
Previous terminal output is cleared on reattaching

### ISSUE THREAD

**Issue by vjlbym** [crigler/dtach#3]
Hi @crigler 

I have been using dtach in a program that I use for executing commands with a long execution time on an Amazon EC2 instance. Due to the instance sometimes being unresponsive, I periodically detach and reattach to the session via my script. It has been working great in general. The only issue I have is that whatever is printed on my local terminal from the redirected output from the instance gets cleared when the session reattaches. So I am not able to see all the output from the session in one place. Is there an easy way to not clear the prior output? 

Thanks a lot!

**Comment by Jiehong** [comment]
I don't think `dtach` would ever support that. Sounds like you want the functionnality of `tmux` or `screen` instead.

You could also think about redirecting the output of your command to a file, or use `less` to be able to scroll through the output being generated.

**Comment by vjlbym** [comment]
Thanks a lot, Jiehong! I wanted to be sure that it's not an inbuilt functionality that I didn't realize. I'll redirect the output. Thanks again!
