### ISSUE TITLE
rpmlint warning: dtach uses __DATE and __TIME__ when it should not

### ISSUE THREAD

**Issue by okurz** [crigler/dtach#8]
## observation

rpmlint warning:
```
W: file-contains-date-and-time /usr/bin/dtach
Your file uses  __DATE and __TIME__ this causes the package to rebuild when
not needed
```

## suggestion

consider if https://reproducible-builds.org/specs/source-date-epoch/ is a viable alternative

**Comment by crigler** [comment]
That rpmlint warning is outdated now that distributions are patching GCC to set `__DATE__` and `__TIME__`  from the `SOURCE_DATE_EPOCH` environment variable.

See:

1. https://wiki.debian.org/ReproducibleBuilds/TimestampsFromCPPMacros
2. https://lists.opensuse.org/opensuse-packaging/2016-06/msg00083.html
3. https://build.opensuse.org/package/view_file/SUSE:SLE-12-SP1:GA/gcc6/gcc6-SOURCE_DATE_EPOCH.patch?expand=1

**Comment by okurz** [comment]
I'm not yet sure if the gcc used for all the distribution versions has this patch included but sure, it's a valid alternative.

**Comment by okurz** [comment]
Sure, that's a valid alternative
